server:
  port: 8082
spring:
  data:
    solr:
      host: http://192.168.154.128:8080/solr
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.154.128:2181
  consumer:
    check: false
image:
  path: http://192.168.154.128/